// Memory Graph Seed (idempotent)
MERGE (p:Project {id:'stepsales', name:'StepSales'})
MERGE (r:Runtime {id:'runtime-local', port:8010, env_path:'environment/.env'})
MERGE (d1:Decision {id:'mem-001', topic:'runtime-port', status:'active'})
MERGE (d2:Decision {id:'mem-002', topic:'env-file-path', status:'active'})
MERGE (rk1:Risk {id:'risk-env-drift', status:'open'})
MERGE (rk2:Risk {id:'risk-memory-stale', status:'open'})
MERGE (t1:Task {id:'task-memory-sync', status:'active'})
MERGE (t2:Task {id:'task-telnyx-setup', status:'done'})
MERGE (t3:Task {id:'task-realtime-enablement', status:'done'})
MERGE (pv1:Provider {id:'provider-telnyx', name:'Telnyx', status:'active'})
MERGE (pv2:Provider {id:'provider-openai', name:'OpenAI', status:'active'})
MERGE (pv3:Provider {id:'provider-deepgram', name:'Deepgram', status:'active'})
MERGE (pv4:Provider {id:'provider-elevenlabs', name:'ElevenLabs', status:'active'})
MERGE (pv5:Provider {id:'provider-stripe', name:'Stripe', status:'active'})
MERGE (g1:Gap {id:'gap-telnyx-setup', status:'closed'})
MERGE (g2:Gap {id:'gap-realtime-pending', status:'closed'})

MERGE (p)-[:HAS_RUNTIME]->(r)
MERGE (p)-[:HAS_DECISION]->(d1)
MERGE (p)-[:HAS_DECISION]->(d2)
MERGE (p)-[:HAS_RISK]->(rk1)
MERGE (p)-[:HAS_RISK]->(rk2)
MERGE (p)-[:NEXT_ACTION]->(t1)
MERGE (p)-[:NEXT_ACTION]->(t2)
MERGE (p)-[:NEXT_ACTION]->(t3)
MERGE (p)-[:USES_PROVIDER]->(pv1)
MERGE (p)-[:USES_PROVIDER]->(pv2)
MERGE (pv1)-[:HAS_GAP]->(g1)
MERGE (p)-[:HAS_GAP]->(g2)
MERGE (t2)-[:ADDRESSES]->(g1)
MERGE (t3)-[:ADDRESSES]->(g2)
MERGE (d2)-[:MITIGATES]->(rk1)
MERGE (t1)-[:MITIGATES]->(rk2)

// Append Log
// New MERGE snippets are appended by .kilo/scripts/memory_write.py

// 2026-04-23T08:14:24Z memory_write append
MERGE (m:Task {id:'mem-004', topic:'kilo-memory', status:'active'})
MERGE (p:Project {id:'stepsales'})
MERGE (p)-[:NEXT_ACTION]->(m)
